Repository AICoE/common, pull requests merged in 2021-09, with the labels that each got.

#21 Create repos for tutorials
  github-config.yaml
Labels: size/S

#20 Add codificat to members of AICoE and thoth station
  github-config.yaml
Labels: size/XS

#17 feat: Add telescope label to d3
  labels.md
  labels.md.tmpl
  labels.yaml
Labels: size/S

#24 a little rewording
  github-config.yaml
Labels: size/S, approved, lgtm

#26 adding tschwesi to Members of Project Meteor
  github-config.yaml
Labels: size/XS, approved, lgtm, ok-to-test

#27 adding ghproxy to prow post-submit jobs
  .prow.yaml
Labels: approved, lgtm

#28 add screeley44
  github-config.yaml
Labels: size/XS, approved, lgtm
