Repository AICoE/common, pull requests merged in 2021-06, with the labels that each got.

#2 feat: Add peribolos without --confirm as presubmit
  .prow.yaml
Labels: size/M

#1 fix: s/master/main/ in Postsubmit CI
  .prow.yaml
Labels: size/XS

#3 feat: Add tumido as admin
  github-config.yaml
Labels: approved, size/XS

#4 feat: Add project meteor repo
  github-config.yaml
Labels: approved, size/S

#6 feat: Add suppathak
  github-config.yaml
Labels: approved, size/XS

#10 feat: Enable labels sync
  .prow.yaml
Labels: approved, size/M

#7 fix: Issue templates not accepted
  .github/ISSUE_TEMPLATE/membership.md
  .github/ISSUE_TEMPLATE/repo-archive.md
  .github/ISSUE_TEMPLATE/repo-create.md
Labels: approved, size/XS

#12 add oindrillac to AICoE and Meteor
  github-config.yaml
Labels: approved, lgtm, size/XS

#13 feat: Add aakankshaduggal
  github-config.yaml
Labels: approved, size/XS

#8 feat: Add D^3 repo
  github-config.yaml
Labels: approved, size/S

#14 Add readme + fix labels job
  .prow.yaml
  README.md
Labels: approved, size/M

#16 Update colors for meteor area labels
  labels.yaml
Labels: approved, size/XS
